apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: compliance-production
  namespace: open-cluster-management
  annotations:
    apps.open-cluster-management.io/github-path: config/compliance/overlays/production
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: open-cluster-management/gitops-repo
  placement:
    placementRef:
      name: production-only
      kind: Placement
      apiGroup: cluster.open-cluster-management.io
