apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-gamma

resources:
  - ../../platform-base
  - app-deployment.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: placeholder
  - patch: |-
      - op: replace
        path: /metadata/name
        value: team-gamma
    target:
      kind: Namespace
      name: placeholder
  - patch: |-
      - op: replace
        path: /subjects/0/name
        value: team-gamma-sres
    target:
      kind: RoleBinding
      name: team-edit-binding
