apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - limitrange.yaml

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
      spec:
        template:
          spec:
            containers:
              - name: nginx
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
