apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: alerting-patch.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: platform-alerts
